services:
    PhpOffice\PhpSpreadsheet\Spreadsheet:
        class: PhpOffice\PhpSpreadsheet\Spreadsheet

    SymfonyImportExportBundle\Services\Exporter:
        arguments:
            $spreadsheet: '@PhpOffice\PhpSpreadsheet\Spreadsheet'
        autowire: true
        autoconfigure: true
        public: true

    SymfonyImportExportBundle\Services\ExporterInterface:
        alias: SymfonyImportExportBundle\Services\Exporter
