services:
    HugoSEIGLE\SymfonyImportExportBundle\Services\MethodToSnakeInterface:
        class: HugoSEIGLE\SymfonyImportExportBundle\Services\MethodToSnake

    HugoSEIGLE\SymfonyImportExportBundle\Services\Export\ExporterInterface:
        alias: HugoSEIGLE\SymfonyImportExportBundle\Services\Export\Exporter

    HugoSEIGLE\SymfonyImportExportBundle\Services\Export\Exporter:
        arguments:
            $methodToSnake: '@HugoSEIGLE\SymfonyImportExportBundle\Services\MethodToSnakeInterface'
            $dateFormat: '%import_export.date_format%'
            $boolTrue: '%import_export.bool_true%'
            $boolFalse: '%import_export.bool_false%'
            $csvDelimiter: '%import_export.csv.delimiter%'
            $csvEnclosure: '%import_export.csv.enclosure%'
            $csvEscape: '%import_export.csv.escape%'
            $csvBom: '%import_export.csv.bom%'
        autowire: true
        autoconfigure: true

    HugoSEIGLE\SymfonyImportExportBundle\Services\Import\ImporterInterface:
        alias: HugoSEIGLE\SymfonyImportExportBundle\Services\Import\Importer

    HugoSEIGLE\SymfonyImportExportBundle\Services\Import\Importer:
        arguments:
            $importers: '%import_export.importers%'
            $dateFormat: '%import_export.date_format%'
            $boolTrue: '%import_export.bool_true%'
            $boolFalse: '%import_export.bool_false%'
            $validateHeaders: '%import_export.validate_headers%'
            $csvDelimiter: '%import_export.csv.delimiter%'
            $csvEnclosure: '%import_export.csv.enclosure%'
            $csvEscape: '%import_export.csv.escape%'
            $methodToSnake: '@HugoSEIGLE\SymfonyImportExportBundle\Services\MethodToSnakeInterface'
        autowire: true
        autoconfigure: true

    HugoSEIGLE\SymfonyImportExportBundle\Services\Import\ImporterTemplateInterface:
        alias: HugoSEIGLE\SymfonyImportExportBundle\Services\Import\ImporterTemplate

    HugoSEIGLE\SymfonyImportExportBundle\Services\Import\ImporterTemplate:
        arguments:
            $importers: '%import_export.importers%'
            $csvDelimiter: '%import_export.csv.delimiter%'
            $csvEnclosure: '%import_export.csv.enclosure%'
            $csvEscape: '%import_export.csv.escape%'
            $csvBom: '%import_export.csv.bom%'
        autowire: true
        autoconfigure: true
