services:
    PhpOffice\PhpSpreadsheet\Spreadsheet:
        class: PhpOffice\PhpSpreadsheet\Spreadsheet
    SymfonyImportExportBundle\Services\MethodToSnakeInterface:
        class: SymfonyImportExportBundle\Services\MethodToSnake

    SymfonyImportExportBundle\Services\Export\ExporterInterface:
        alias: SymfonyImportExportBundle\Services\Export\Exporter

    SymfonyImportExportBundle\Services\Export\Exporter:
        arguments:
            $spreadsheet: '@PhpOffice\PhpSpreadsheet\Spreadsheet'
            $methodToSnake: '@SymfonyImportExportBundle\Services\MethodToSnakeInterface'
            $dateFormat: '%import_export.date_format%'
            $boolTrue: '%import_export.bool_true%'
            $boolFalse: '%import_export.bool_false%'
        autowire: true
        autoconfigure: true
        public: true

    SymfonyImportExportBundle\Services\Import\ImporterInterface:
        alias: SymfonyImportExportBundle\Services\Import\Importer

    SymfonyImportExportBundle\Services\Import\Importer:
        arguments:
            $boolTrue: '%import_export.bool_true%'
        autowire: true
        autoconfigure: true
        public: true

    SymfonyImportExportBundle\Services\Import\ImporterTemplateInterface:
        alias: SymfonyImportExportBundle\Services\Import\ImporterTemplate

    SymfonyImportExportBundle\Services\Import\ImporterTemplate:
        autowire: true
        autoconfigure: true
        public: true
