services:
    SymfonyImportExportBundle\Services\Exporter:
        autowire: true
        autoconfigure: true
        public: true

    SymfonyImportExportBundle\Services\ExporterInterface:
        alias: SymfonyImportExportBundle\Services\Exporter
