services:
    PhpOffice\PhpSpreadsheet\Spreadsheet:
        class: PhpOffice\PhpSpreadsheet\Spreadsheet
        shared: false
    SymfonyImportExportBundle\Services\MethodToSnakeInterface:
        class: SymfonyImportExportBundle\Services\MethodToSnake

    SymfonyImportExportBundle\Services\Export\ExporterInterface:
        alias: SymfonyImportExportBundle\Services\Export\Exporter

    SymfonyImportExportBundle\Services\Export\Exporter:
        arguments:
            $spreadsheet: '@PhpOffice\PhpSpreadsheet\Spreadsheet'
            $methodToSnake: '@SymfonyImportExportBundle\Services\MethodToSnakeInterface'
            $dateFormat: '%import_export.date_format%'
            $boolTrue: '%import_export.bool_true%'
            $boolFalse: '%import_export.bool_false%'
            $csvDelimiter: '%import_export.csv.delimiter%'
            $csvEnclosure: '%import_export.csv.enclosure%'
            $csvEscape: '%import_export.csv.escape%'
            $csvBom: '%import_export.csv.bom%'
        autowire: true
        autoconfigure: true

    SymfonyImportExportBundle\Services\Import\ImporterInterface:
        alias: SymfonyImportExportBundle\Services\Import\Importer

    SymfonyImportExportBundle\Services\Import\Importer:
        arguments:
            $boolTrue: '%import_export.bool_true%'
            $boolFalse: '%import_export.bool_false%'
            $validateHeaders: '%import_export.validate_headers%'
            $csvDelimiter: '%import_export.csv.delimiter%'
            $csvEnclosure: '%import_export.csv.enclosure%'
            $csvEscape: '%import_export.csv.escape%'
            $methodToSnake: '@SymfonyImportExportBundle\Services\MethodToSnakeInterface'
        autowire: true
        autoconfigure: true

    SymfonyImportExportBundle\Services\Import\ImporterTemplateInterface:
        alias: SymfonyImportExportBundle\Services\Import\ImporterTemplate

    SymfonyImportExportBundle\Services\Import\ImporterTemplate:
        arguments:
            $csvDelimiter: '%import_export.csv.delimiter%'
            $csvEnclosure: '%import_export.csv.enclosure%'
            $csvEscape: '%import_export.csv.escape%'
            $csvBom: '%import_export.csv.bom%'
        autowire: true
        autoconfigure: true
